### ISSUE TITLE
Add Submit form button while creating form

### ISSUE THREAD

**Issue by farhanmeo** [Kiho/react-form-builder#163]
Currently the API get hit after every field drag and drop which can cost a lot also not  efficient way e.g if I have to create a form with 50 fields and I am using firebase functions my functions will get hit 50 times now multiply this by 100 users. 5000 hts or firebase can cost a lot. 

Expected: API should not get hit on every drag and drop, there should be submit button after a user is done with for he will press that button and only one API hit will save the form

**Comment by Kiho** [comment]
I don't have much option with form post, if you expect a lot of usage then you can handle it with custom API call like this example.
https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L85

**Comment by farhanmeo** [comment]
But this will not reduce the API hits on server, Actually what I am looking
for is if I drop field it should not hit the API, API should only be hit
once save form is pressed

**Comment by Kiho** [comment]
You can implement that by yourself. you just need to wrap rfb in your application and add save button there.

**Comment by Kiho** [comment]
```js
  onPost = (data) => {
    if (!this.batchData) {
       this.batchData = [];
    }
    this.batchData.push(data);
  };
```
Then you can post `this.batchData` to back-end by your save button.
Also you you need to clean up data after posting like `this.batchData = [];`

**Comment by farhanmeo** [comment]
How will I stop hit on every drag and drop field?

**Comment by Kiho** [comment]
If you set onPost attribute ReactFormBuilder then form post will not happen.

**Comment by kart1ka** [comment]
Hey @farhanmeo. In order to post form data to the backend on the click of a specific button, you can declare a state (say `formData`) in your component. Then access `data` from the store using `ElementStore.subscribe` and set the value of formData state to the value of the `data`  as shown below. 
In order to stop the ReactFormBuilder from hitting your backend on every drag and drop, you can pass an empty `onPost` function to the `ReactFormBuilder` with nothing but a return statement inside it. Then you can post form data that is now stored inside your `formData` state to the backend whenever the button is clicked.

Remember to `import { ElementStore } from "react-form-builder2";`


```
const [formData, setFormData] = useState([]);

  ElementStore.subscribe((state) => {
    setFormData(state.data);
  });


  const onPost = () => {
    return;
  }

  const onPostHandler = () => {
    const url = "firebaseUrl"

    post(url, { task_data: formData });

    console.log(formData);
  };

  return (
    <div>
      <ReactFormBuilder onPost={onPost} />
      <button onClick={onPostHandler}>Press it</button>
    </div>
  );
```
