### ISSUE TITLE
Multiple Form Builders

### ISSUE THREAD

**Issue by Sandlee09** [Kiho/react-form-builder#229]
Any idea how I would go about having 2 formbuilders on the same page?

**Comment by Kiho** [comment]
You can find  example of multiple form instance here https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js and snippets of server side code here https://github.com/Kiho/react-form-builder/issues/101

**Comment by jemikanegara** [comment]
@Kiho looks like that example only demonstrate multiple form generators, not multiple form builders

the issue is when put multiple form builders in one page, if we click toolbar one one form builder, it got added on the other form builder too, looks like the issue coming from the beedle store (because the instance shared accross formbuilders)

**Comment by Kiho** [comment]
It is separated by server, unfortunately you can interact with only single client at a time.
